name: Make It With Code Blog
description: "Teaching people to code by making things, not learning Syntax"
meta_description: "Official Make It With Code Blog. How we teach people to make things with code, not just write code"

permalink: /:year/:month/:title

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://www.makeitwithcode.com/blog/'
author:         'Make It With Code'
baseurl: '/blog'

exclude: [Rakefile, README.md, Capfile, Gemfile, Gemfile.lock, config/, lib/]
encoding: utf-8